# -*- coding: utf-8 -*-
"""BSD3513_LAB REPORT 1_SD23013.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFz-uyD23vRtWe37LkZ4ju137P3yB08d

BSD3513 INTRODUCTION TO ARTIFICIAL INTELLIGENCE LAB REPORT 1

NAME: AIN MARDHIAH BINTI ABDUL HAMID

ID: SD23013
"""

from IPython.display import Image
Image("/content/LabReport_BSD2513_#1.jpg")

"""(a) Breadth First Search (BFS) Algorithm"""

graph = {
  'A' : ['B','D'],
  'B' : ['C', 'E','G'],
  'C' : ['A'],
  'D' : ['C'],
  'E' : ['H'],
  'F' : [],
  'G' : ['F'],
  'H' : ['G']
}

visited = []
queue = []

def bfs(visited, graph, node):
  visited.append(node)
  queue.append(node)

  while queue:
    s = queue.pop(0)
    print (s, end = " ")

    for neighbour in graph[s]:
      if neighbour not in visited:
        visited.append(neighbour)
        queue.append(neighbour)

# Driver Code
print("Following is the Breadth-First Search")
bfs(visited, graph, 'A')

"""(b) Depth First Search (DFS) Algorithm"""

graph = {
  'A' : ['B','D'],
  'B' : ['C', 'E','G'],
  'C' : ['A'],
  'D' : ['C'],
  'E' : ['H'],
  'F' : [],
  'G' : ['F'],
  'H' : ['G']
}

visited = set()

def dfs(visited, graph, node):
    if node not in visited:
        print (node)
        visited.add(node)
        for neighbour in graph[node]:
            dfs(visited, graph, neighbour)

# Driver Code
print("Following is the Depth-First Search")
dfs(visited, graph, 'A')